### ISSUE TITLE
material-ui v1 support

### ISSUE THREAD

**Issue by Jf881** [TeamWertarbyte/material-ui-chip-input#147] opened 2017-09-22 08:58 UTC
When using material-ui@next ChipInput breaks because of changes to material-ui. For example:
Can't resolve 'material-ui/TextField/TextFieldUnderline'
Can't resolve 'material-ui/TextField/TextFieldHint'
...and material-ui/styles/colors has moved to material-ui/colors.
Any chance of an update soon?

Steps to reproduce:
>create-react-app example
>cd example
>yarn add material-ui@next
>yarn add material-ui-chip-input
Add "import ChipInput from 'material-ui-chip-input' " in App.js
>yarn start

Thx!
/J

**Comment by leMaik** [comment] 2017-09-22 09:01
This component doesn't support v1 of material-ui yet. There are lots of breaking changes, unfortunately, so it will take a while. But we're definitely planning to support it!

**Comment by leMaik** [comment] 2017-09-22 09:02
Uhm… Actually, this is a duplicate of #88

**Closed by leMaik** 2017-09-22 09:02 UTC
Labels: feature request, material-ui

**Comment by Jf881** [comment] 2017-09-22 09:07
Thx for superfast reply, missed that one.
/J
