### ISSUE TITLE
Auto open on focus bug/ feature

### ISSUE THREAD

**Issue by TeeShastry** [TeamWertarbyte/material-ui-chip-input#39] opened 2016-11-10 16:23 UTC
Hi, 

I am having an issue with the control. I am using autocomplete with openonfocus for the Chipinput control and my expecetd behaviour is as soon as I select an option, it should open the dropdown automatically.
But what I see is once I select the option I need to click the mouse two times to open the dropdown, sometimes I need change the cursor position before clicking on it to open it. Basically once the user selects an option it should autofocus and keep the dropdownlist open since the user might want to select other options. Is this something that you can fix and also add this feature?

Thanks,
Tee

**Comment by leMaik** [comment] 2016-11-10 16:40
Duplicate of #11

**Closed by leMaik** 2016-11-10 16:40 UTC

**Comment by TeeShastry** [comment] 2016-11-10 18:00
Thank you!
