### ISSUE TITLE
Webpack throws error after babel-plugin-transform-object-assign was added

### ISSUE THREAD

**Issue by ajdalshov** [TeamWertarbyte/material-ui-chip-input#62] opened 2016-12-16 06:58 UTC
ERROR in ./~/material-ui-chip-input/lib/ChipInput.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign"

**Comment by leMaik** [comment] 2016-12-16 08:36
I can't reproduce this bug. Could you please explain to me when this occurs or perhaps even add a minimal example? Thanks in advance!

**Comment by leMaik** [comment] 2017-01-19 14:45
Closing this after a month without any response. :disappointed:

**Closed by leMaik** 2017-01-19 14:45 UTC
Labels: invalid
