### ISSUE TITLE
ChipInput closes IME input dialog after each key press

### ISSUE THREAD

**Issue by matsumatsu233** [TeamWertarbyte/material-ui-chip-input#144] opened 2017-09-13 08:37 UTC
For example, if I want to input Chinese word 你好, I will type **n, i, h, a, o, space**.
The IME dialog comes out after key pressing, but it disappears in a flash, and leaving only the letters (nihao) on the input field. So it means that I cannot transform letters to Chinese Character. Also Japanese has the some issue.

I found out that this issue comes out from v0.17.0, until v0.16.1 it works well.

**Comment by leMaik** [comment] 2017-09-13 09:21
Hm, I don't know what causes this, the changes in v0.17.0 are [pretty small](https://github.com/TeamWertarbyte/material-ui-chip-input/commit/dcca47af6a82ba86500043692e15d7da07849e58). Unfortunately, I can't reproduce IME issues here.

Any help or maybe even a PR would be greatly appreciated! :+1:

**Comment by matsumatsu233** [comment] 2017-09-13 09:34
I guess the mui's version change causes this issue. I've tried to fix it but failed :(

Forgot to say that on the mobile phone it behaves even stranger. The IME doesn't disappear. But if I type 你好 for example, after each pressing the text on IME will be appended to text field. So finally the text becomes something like "nninihnihanihao".

**Comment by leMaik** [comment] 2017-09-13 09:39
Strange :confused: 
@foloinfo You did some great work in fixing IME bugs before, would you mind taking a look on this? :smile:

**Comment by foloinfo** [comment] 2017-09-13 11:29
Hi, I haven't updated for a while so I updated the package from 0.15.3 to 0.17.2 and tested, and it works fine in both versions.
I tested with Japanese IME and I added Chinese IME but seems like it is working as well.
I'm using Google Japanese Input and MacOS's default IME for Chinese. I'm using react 15.6.1, material-ui 0.18.7.

I looked at code diff as well, but it seems like those changes are not related to IME behaviour.
So IMHO I suspect this bug is caused by something else.

I cannot replicate the bug so it's difficult to track it down, but I think I had a similar problem before.
In my case the problem was caused by handling state that was updating my component each time I hit keys. I stopped passing around states and props and the problem was solved.

I'm not sure if these info helps, but more details about your situation might give me some clue.

**Comment by matsumatsu233** [comment] 2017-09-13 11:54
Hi @foloinfo, your info helps a lot, thank you!

I just cloned this repo and ran the storybook to test its behavior. So my material-ui's version is 0.19.1. Also when I first found this bug on my own project, I was using 0.19.1.

I've tried to downgrade material-ui to 0.18.7 and found that it is working well both for Japanese and Chinese IME as you mentioned. And I guess you could replicate it with material-ui 0.19.1.

**Comment by foloinfo** [comment] 2017-09-13 12:25
@matsumatsu233 I'm grad to hear that!
So there is an issue with that version of material-ui. For now material-ui v1 is coming and seems like they are rebuilding texfield component from ground up, so I guess I'll stick to 0.18.7.
If you are ganna tackle this problem and need some help, feel free to mention me. :)

**Comment by leMaik** [comment] 2017-09-13 12:38
@foloinfo Thank you very much for your help! :)

**Comment by leMaik** [comment] 2018-08-27 11:40
@foloinfo @matsumatsu233 I'm closing this because I can't reproduce it and I'm unable to fix these kind of bugs. Please don't hesitate to open a new issue if you encounter any IME bugs. :+1:

**Closed by leMaik** 2018-08-27 11:40 UTC
Labels: bug
