### ISSUE TITLE
Error when dataSource property is an array of objects instead of an array of strings

### ISSUE THREAD

**Issue by pramttl** [TeamWertarbyte/material-ui-chip-input#15] opened 2016-09-30 06:37 UTC
The following error poups up in console when `dataSource` prop is an array of objects, instead of array of strings. 
```
Failed prop type: Invalid prop `dataSource[0]` of type `object` supplied to `ChipInput`, expected `string`.
```
When the error occurs, the chip input does not work as expected. The dropdown still appears and shows the text correctly but after selecting an element a chip does not show up in the `ChipInput`.

Example:

This causes error:

```
<ChipInput
    // Other props
    dataSource={ [{'text': 'Chip1', value: 1},  {'text': 'Chip2', value: 2}, ] }
/>
```

This does not:

```
<ChipInput
    // Other props
    dataSource={ ['Chip1', 'Chip2',] }
/>
```

**Ideal Behavior**

`dataSource` being array of objects should also work for `ChipInput` and not just array of strings. Since `AutoComplete` in mui allows array of objects, I expected similar behaviour here.

**Comment by leMaik** [comment] 2016-09-30 08:08
Duplicate of #9. I'll add this feature soon. :wink:

**Closed by leMaik** 2016-09-30 08:08 UTC
Labels: duplicate
